### ISSUE TITLE
multiple dx circuits

### ISSUE THREAD

**Issue by michaeldoddgit** [awslabs/aws-dx-monitor#2]
The monitor appears to work fine if you have a single Dx circuit. If you have multiple dx circuits for redundancy, then only the vif's on the first circuit, but not the second, appear to be able to be monitored.

**Comment by rpcme** [comment]
Hello toy4two, I am sorry I didn't see a notification for this issue - probably lost due to re:Invent happenings.  Do you still have the issue?  If so, I can check into it.

**Comment by michaeldoddgit** [comment]
thank you rpcme.  There is an issue, but working with AWS support we can't nail down where it is.  We've scrubbed and redeployed in the region it is not working to no avail.  It does seem to work in our N.Virginia region with multiple circuits.  

CloudWatch metrics are sporadic on some virtual network interfaces, fine on others, and completely blank on yet others.  The problem only appears to happen on one of two Dx connections, but the Dx team assures us the connection is up and working 100% and blames this "unsupported" cloudwatch metric.

**Comment by michaeldoddgit** [comment]
It appears the problem is multiple circuits, or connections in Dx speak, in some regions.  We were able to fix the problem by changing the default lambda timeout value of 3 seconds to 10 seconds.  Before it would timeout before reading all the Dx information.  3 seconds was enough time for a single Dx connection, but for multiple connections, in some regions only, 3 seconds wasn't enough time.

The other thing I would mention, for new folks deploying this, AWS changed their CloudWatch Lambda deployment page, and the instructions here still apply but finding the new fields is a challange.

**Comment by rpcme** [comment]
Hello @toy4two  - let me work through the updated instructions.

**Comment by rpcme** [comment]
@toy4two sorry for the lateness - will see if I can get this done next week with the python interpreter migration work.  I also hope to get the instructions all wrapped up in cloudformation so there won't be any weirdness with the instructions any longer.

**Comment by rpcme** [comment]
This is fixed in the new SAM CLI script with timeout of 40 seconds.
