### ISSUE TITLE
Missing Transit Gateway & Direct Connect Gateway State

### ISSUE THREAD

**Issue by githubnoobieme** [awslabs/aws-dx-monitor#3]
Hello,

since the direct connect service had expanded, it would be nice if transit gateway & direct connect gateways could also be monitored.

BR

**Comment by rpcme** [comment]
Hello @githubnoobieme - happy to look into it! Of course, pull requests are welcome.  Could you let me know the urgency of this request?  Are you looking to use the functionality ASAP?
