### ISSUE TITLE
Migrate to Python 3?

### ISSUE THREAD

**Issue by mdimarino** [awslabs/aws-dx-monitor#6]
Any chance to migrate it to Python 3, since AWS will deprecate support to Python 2.7 on July 15, 2021?

Thanks!

**Comment by rpcme** [comment]
Hello @mdimarino I am checking on if I have a test bed internally I can test against.  In general, it must be updated.  I can invoke it, but I won't be able to integrate test it unless I have a test bed.

**Comment by rpcme** [comment]
@mdimarino the project has been updated to use Python 3.8.  We are still testing, but I wanted to let you know that we have progress on this effort in order to reduce the operational burden/risk with Python 2.7 EOL.

**Comment by mdimarino** [comment]
Thank you!

Em qua., 14 de abr. de 2021 às 15:59, Richard Elberger <
***@***.***> escreveu:

**Comment by rpcme** [comment]
Hello @mdimarino I will be closing this issue now.  Please let us know if you face any issue ok?
